# Generated by Django 4.1.1 on 2022-09-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Horoscope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sign", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("horoscope", models.TextField()),
            ],
        ),
    ]
